// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: options.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_options_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_options_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_options_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_options_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_options_2eproto;
namespace options {
class HestonOptionPricingRequest;
struct HestonOptionPricingRequestDefaultTypeInternal;
extern HestonOptionPricingRequestDefaultTypeInternal _HestonOptionPricingRequest_default_instance_;
class HestonOptionPricingResponse;
struct HestonOptionPricingResponseDefaultTypeInternal;
extern HestonOptionPricingResponseDefaultTypeInternal _HestonOptionPricingResponse_default_instance_;
class ScholesOptionPricingRequest;
struct ScholesOptionPricingRequestDefaultTypeInternal;
extern ScholesOptionPricingRequestDefaultTypeInternal _ScholesOptionPricingRequest_default_instance_;
class ScholesOptionPricingResponse;
struct ScholesOptionPricingResponseDefaultTypeInternal;
extern ScholesOptionPricingResponseDefaultTypeInternal _ScholesOptionPricingResponse_default_instance_;
class VarianceGammaOptionPricingRequest;
struct VarianceGammaOptionPricingRequestDefaultTypeInternal;
extern VarianceGammaOptionPricingRequestDefaultTypeInternal _VarianceGammaOptionPricingRequest_default_instance_;
class VarianceGammaOptionPricingResponse;
struct VarianceGammaOptionPricingResponseDefaultTypeInternal;
extern VarianceGammaOptionPricingResponseDefaultTypeInternal _VarianceGammaOptionPricingResponse_default_instance_;
}  // namespace options
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace options {

// ===================================================================


// -------------------------------------------------------------------

class VarianceGammaOptionPricingResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.VarianceGammaOptionPricingResponse) */ {
 public:
  inline VarianceGammaOptionPricingResponse() : VarianceGammaOptionPricingResponse(nullptr) {}
  ~VarianceGammaOptionPricingResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VarianceGammaOptionPricingResponse(::google::protobuf::internal::ConstantInitialized);

  inline VarianceGammaOptionPricingResponse(const VarianceGammaOptionPricingResponse& from)
      : VarianceGammaOptionPricingResponse(nullptr, from) {}
  VarianceGammaOptionPricingResponse(VarianceGammaOptionPricingResponse&& from) noexcept
    : VarianceGammaOptionPricingResponse() {
    *this = ::std::move(from);
  }

  inline VarianceGammaOptionPricingResponse& operator=(const VarianceGammaOptionPricingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline VarianceGammaOptionPricingResponse& operator=(VarianceGammaOptionPricingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VarianceGammaOptionPricingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const VarianceGammaOptionPricingResponse* internal_default_instance() {
    return reinterpret_cast<const VarianceGammaOptionPricingResponse*>(
               &_VarianceGammaOptionPricingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(VarianceGammaOptionPricingResponse& a, VarianceGammaOptionPricingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(VarianceGammaOptionPricingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VarianceGammaOptionPricingResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VarianceGammaOptionPricingResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VarianceGammaOptionPricingResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VarianceGammaOptionPricingResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const VarianceGammaOptionPricingResponse& from) {
    VarianceGammaOptionPricingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VarianceGammaOptionPricingResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.VarianceGammaOptionPricingResponse";
  }
  protected:
  explicit VarianceGammaOptionPricingResponse(::google::protobuf::Arena* arena);
  VarianceGammaOptionPricingResponse(::google::protobuf::Arena* arena, const VarianceGammaOptionPricingResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOptionPriceFieldNumber = 1,
  };
  // double option_price = 1;
  void clear_option_price() ;
  double option_price() const;
  void set_option_price(double value);

  private:
  double _internal_option_price() const;
  void _internal_set_option_price(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.VarianceGammaOptionPricingResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double option_price_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};// -------------------------------------------------------------------

class VarianceGammaOptionPricingRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.VarianceGammaOptionPricingRequest) */ {
 public:
  inline VarianceGammaOptionPricingRequest() : VarianceGammaOptionPricingRequest(nullptr) {}
  ~VarianceGammaOptionPricingRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VarianceGammaOptionPricingRequest(::google::protobuf::internal::ConstantInitialized);

  inline VarianceGammaOptionPricingRequest(const VarianceGammaOptionPricingRequest& from)
      : VarianceGammaOptionPricingRequest(nullptr, from) {}
  VarianceGammaOptionPricingRequest(VarianceGammaOptionPricingRequest&& from) noexcept
    : VarianceGammaOptionPricingRequest() {
    *this = ::std::move(from);
  }

  inline VarianceGammaOptionPricingRequest& operator=(const VarianceGammaOptionPricingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VarianceGammaOptionPricingRequest& operator=(VarianceGammaOptionPricingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VarianceGammaOptionPricingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VarianceGammaOptionPricingRequest* internal_default_instance() {
    return reinterpret_cast<const VarianceGammaOptionPricingRequest*>(
               &_VarianceGammaOptionPricingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VarianceGammaOptionPricingRequest& a, VarianceGammaOptionPricingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VarianceGammaOptionPricingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VarianceGammaOptionPricingRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VarianceGammaOptionPricingRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VarianceGammaOptionPricingRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VarianceGammaOptionPricingRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const VarianceGammaOptionPricingRequest& from) {
    VarianceGammaOptionPricingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VarianceGammaOptionPricingRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.VarianceGammaOptionPricingRequest";
  }
  protected:
  explicit VarianceGammaOptionPricingRequest(::google::protobuf::Arena* arena);
  VarianceGammaOptionPricingRequest(::google::protobuf::Arena* arena, const VarianceGammaOptionPricingRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnderlyingPriceFieldNumber = 1,
    kStrikePriceFieldNumber = 2,
    kTimeToExpirationFieldNumber = 3,
    kRiskFreeInterestRateFieldNumber = 4,
    kDriftRateFieldNumber = 5,
    kVolatilityFieldNumber = 6,
    kMeanReversionParameterFieldNumber = 7,
    kJumpIntensityFieldNumber = 8,
    kJumpSizeDistributionFieldNumber = 9,
  };
  // double underlying_price = 1;
  void clear_underlying_price() ;
  double underlying_price() const;
  void set_underlying_price(double value);

  private:
  double _internal_underlying_price() const;
  void _internal_set_underlying_price(double value);

  public:
  // double strike_price = 2;
  void clear_strike_price() ;
  double strike_price() const;
  void set_strike_price(double value);

  private:
  double _internal_strike_price() const;
  void _internal_set_strike_price(double value);

  public:
  // double time_to_expiration = 3;
  void clear_time_to_expiration() ;
  double time_to_expiration() const;
  void set_time_to_expiration(double value);

  private:
  double _internal_time_to_expiration() const;
  void _internal_set_time_to_expiration(double value);

  public:
  // double risk_free_interest_rate = 4;
  void clear_risk_free_interest_rate() ;
  double risk_free_interest_rate() const;
  void set_risk_free_interest_rate(double value);

  private:
  double _internal_risk_free_interest_rate() const;
  void _internal_set_risk_free_interest_rate(double value);

  public:
  // double drift_rate = 5;
  void clear_drift_rate() ;
  double drift_rate() const;
  void set_drift_rate(double value);

  private:
  double _internal_drift_rate() const;
  void _internal_set_drift_rate(double value);

  public:
  // double volatility = 6;
  void clear_volatility() ;
  double volatility() const;
  void set_volatility(double value);

  private:
  double _internal_volatility() const;
  void _internal_set_volatility(double value);

  public:
  // double mean_reversion_parameter = 7;
  void clear_mean_reversion_parameter() ;
  double mean_reversion_parameter() const;
  void set_mean_reversion_parameter(double value);

  private:
  double _internal_mean_reversion_parameter() const;
  void _internal_set_mean_reversion_parameter(double value);

  public:
  // double jump_intensity = 8;
  void clear_jump_intensity() ;
  double jump_intensity() const;
  void set_jump_intensity(double value);

  private:
  double _internal_jump_intensity() const;
  void _internal_set_jump_intensity(double value);

  public:
  // double jump_size_distribution = 9;
  void clear_jump_size_distribution() ;
  double jump_size_distribution() const;
  void set_jump_size_distribution(double value);

  private:
  double _internal_jump_size_distribution() const;
  void _internal_set_jump_size_distribution(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.VarianceGammaOptionPricingRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double underlying_price_;
    double strike_price_;
    double time_to_expiration_;
    double risk_free_interest_rate_;
    double drift_rate_;
    double volatility_;
    double mean_reversion_parameter_;
    double jump_intensity_;
    double jump_size_distribution_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};// -------------------------------------------------------------------

class ScholesOptionPricingResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.ScholesOptionPricingResponse) */ {
 public:
  inline ScholesOptionPricingResponse() : ScholesOptionPricingResponse(nullptr) {}
  ~ScholesOptionPricingResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ScholesOptionPricingResponse(::google::protobuf::internal::ConstantInitialized);

  inline ScholesOptionPricingResponse(const ScholesOptionPricingResponse& from)
      : ScholesOptionPricingResponse(nullptr, from) {}
  ScholesOptionPricingResponse(ScholesOptionPricingResponse&& from) noexcept
    : ScholesOptionPricingResponse() {
    *this = ::std::move(from);
  }

  inline ScholesOptionPricingResponse& operator=(const ScholesOptionPricingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScholesOptionPricingResponse& operator=(ScholesOptionPricingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScholesOptionPricingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScholesOptionPricingResponse* internal_default_instance() {
    return reinterpret_cast<const ScholesOptionPricingResponse*>(
               &_ScholesOptionPricingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ScholesOptionPricingResponse& a, ScholesOptionPricingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ScholesOptionPricingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScholesOptionPricingResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScholesOptionPricingResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScholesOptionPricingResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScholesOptionPricingResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ScholesOptionPricingResponse& from) {
    ScholesOptionPricingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ScholesOptionPricingResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.ScholesOptionPricingResponse";
  }
  protected:
  explicit ScholesOptionPricingResponse(::google::protobuf::Arena* arena);
  ScholesOptionPricingResponse(::google::protobuf::Arena* arena, const ScholesOptionPricingResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOptionPriceFieldNumber = 1,
  };
  // double option_price = 1;
  void clear_option_price() ;
  double option_price() const;
  void set_option_price(double value);

  private:
  double _internal_option_price() const;
  void _internal_set_option_price(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.ScholesOptionPricingResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double option_price_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};// -------------------------------------------------------------------

class ScholesOptionPricingRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.ScholesOptionPricingRequest) */ {
 public:
  inline ScholesOptionPricingRequest() : ScholesOptionPricingRequest(nullptr) {}
  ~ScholesOptionPricingRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ScholesOptionPricingRequest(::google::protobuf::internal::ConstantInitialized);

  inline ScholesOptionPricingRequest(const ScholesOptionPricingRequest& from)
      : ScholesOptionPricingRequest(nullptr, from) {}
  ScholesOptionPricingRequest(ScholesOptionPricingRequest&& from) noexcept
    : ScholesOptionPricingRequest() {
    *this = ::std::move(from);
  }

  inline ScholesOptionPricingRequest& operator=(const ScholesOptionPricingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScholesOptionPricingRequest& operator=(ScholesOptionPricingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScholesOptionPricingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ScholesOptionPricingRequest* internal_default_instance() {
    return reinterpret_cast<const ScholesOptionPricingRequest*>(
               &_ScholesOptionPricingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ScholesOptionPricingRequest& a, ScholesOptionPricingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ScholesOptionPricingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScholesOptionPricingRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScholesOptionPricingRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ScholesOptionPricingRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScholesOptionPricingRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ScholesOptionPricingRequest& from) {
    ScholesOptionPricingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ScholesOptionPricingRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.ScholesOptionPricingRequest";
  }
  protected:
  explicit ScholesOptionPricingRequest(::google::protobuf::Arena* arena);
  ScholesOptionPricingRequest(::google::protobuf::Arena* arena, const ScholesOptionPricingRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnderlyingPriceFieldNumber = 1,
    kStrikePriceFieldNumber = 2,
    kTimeToExpirationFieldNumber = 3,
    kRiskFreeInterestRateFieldNumber = 4,
    kVolatilityFieldNumber = 5,
  };
  // double underlying_price = 1;
  void clear_underlying_price() ;
  double underlying_price() const;
  void set_underlying_price(double value);

  private:
  double _internal_underlying_price() const;
  void _internal_set_underlying_price(double value);

  public:
  // double strike_price = 2;
  void clear_strike_price() ;
  double strike_price() const;
  void set_strike_price(double value);

  private:
  double _internal_strike_price() const;
  void _internal_set_strike_price(double value);

  public:
  // double time_to_expiration = 3;
  void clear_time_to_expiration() ;
  double time_to_expiration() const;
  void set_time_to_expiration(double value);

  private:
  double _internal_time_to_expiration() const;
  void _internal_set_time_to_expiration(double value);

  public:
  // double risk_free_interest_rate = 4;
  void clear_risk_free_interest_rate() ;
  double risk_free_interest_rate() const;
  void set_risk_free_interest_rate(double value);

  private:
  double _internal_risk_free_interest_rate() const;
  void _internal_set_risk_free_interest_rate(double value);

  public:
  // double volatility = 5;
  void clear_volatility() ;
  double volatility() const;
  void set_volatility(double value);

  private:
  double _internal_volatility() const;
  void _internal_set_volatility(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.ScholesOptionPricingRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double underlying_price_;
    double strike_price_;
    double time_to_expiration_;
    double risk_free_interest_rate_;
    double volatility_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};// -------------------------------------------------------------------

class HestonOptionPricingResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.HestonOptionPricingResponse) */ {
 public:
  inline HestonOptionPricingResponse() : HestonOptionPricingResponse(nullptr) {}
  ~HestonOptionPricingResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HestonOptionPricingResponse(::google::protobuf::internal::ConstantInitialized);

  inline HestonOptionPricingResponse(const HestonOptionPricingResponse& from)
      : HestonOptionPricingResponse(nullptr, from) {}
  HestonOptionPricingResponse(HestonOptionPricingResponse&& from) noexcept
    : HestonOptionPricingResponse() {
    *this = ::std::move(from);
  }

  inline HestonOptionPricingResponse& operator=(const HestonOptionPricingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline HestonOptionPricingResponse& operator=(HestonOptionPricingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HestonOptionPricingResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const HestonOptionPricingResponse* internal_default_instance() {
    return reinterpret_cast<const HestonOptionPricingResponse*>(
               &_HestonOptionPricingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HestonOptionPricingResponse& a, HestonOptionPricingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(HestonOptionPricingResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HestonOptionPricingResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HestonOptionPricingResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HestonOptionPricingResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HestonOptionPricingResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HestonOptionPricingResponse& from) {
    HestonOptionPricingResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HestonOptionPricingResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.HestonOptionPricingResponse";
  }
  protected:
  explicit HestonOptionPricingResponse(::google::protobuf::Arena* arena);
  HestonOptionPricingResponse(::google::protobuf::Arena* arena, const HestonOptionPricingResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOptionPriceFieldNumber = 1,
  };
  // double option_price = 1;
  void clear_option_price() ;
  double option_price() const;
  void set_option_price(double value);

  private:
  double _internal_option_price() const;
  void _internal_set_option_price(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.HestonOptionPricingResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double option_price_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};// -------------------------------------------------------------------

class HestonOptionPricingRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:options.HestonOptionPricingRequest) */ {
 public:
  inline HestonOptionPricingRequest() : HestonOptionPricingRequest(nullptr) {}
  ~HestonOptionPricingRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR HestonOptionPricingRequest(::google::protobuf::internal::ConstantInitialized);

  inline HestonOptionPricingRequest(const HestonOptionPricingRequest& from)
      : HestonOptionPricingRequest(nullptr, from) {}
  HestonOptionPricingRequest(HestonOptionPricingRequest&& from) noexcept
    : HestonOptionPricingRequest() {
    *this = ::std::move(from);
  }

  inline HestonOptionPricingRequest& operator=(const HestonOptionPricingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HestonOptionPricingRequest& operator=(HestonOptionPricingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HestonOptionPricingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HestonOptionPricingRequest* internal_default_instance() {
    return reinterpret_cast<const HestonOptionPricingRequest*>(
               &_HestonOptionPricingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HestonOptionPricingRequest& a, HestonOptionPricingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HestonOptionPricingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HestonOptionPricingRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HestonOptionPricingRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HestonOptionPricingRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HestonOptionPricingRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const HestonOptionPricingRequest& from) {
    HestonOptionPricingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(HestonOptionPricingRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "options.HestonOptionPricingRequest";
  }
  protected:
  explicit HestonOptionPricingRequest(::google::protobuf::Arena* arena);
  HestonOptionPricingRequest(::google::protobuf::Arena* arena, const HestonOptionPricingRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnderlyingPriceFieldNumber = 1,
    kStrikePriceFieldNumber = 2,
    kTimeToExpirationFieldNumber = 3,
    kRiskFreeInterestRateFieldNumber = 4,
    kInitialVolatilityFieldNumber = 5,
    kMeanReversionRateFieldNumber = 6,
    kVolatilityOfVolatilityFieldNumber = 7,
    kCorrelationFieldNumber = 8,
  };
  // double underlying_price = 1;
  void clear_underlying_price() ;
  double underlying_price() const;
  void set_underlying_price(double value);

  private:
  double _internal_underlying_price() const;
  void _internal_set_underlying_price(double value);

  public:
  // double strike_price = 2;
  void clear_strike_price() ;
  double strike_price() const;
  void set_strike_price(double value);

  private:
  double _internal_strike_price() const;
  void _internal_set_strike_price(double value);

  public:
  // double time_to_expiration = 3;
  void clear_time_to_expiration() ;
  double time_to_expiration() const;
  void set_time_to_expiration(double value);

  private:
  double _internal_time_to_expiration() const;
  void _internal_set_time_to_expiration(double value);

  public:
  // double risk_free_interest_rate = 4;
  void clear_risk_free_interest_rate() ;
  double risk_free_interest_rate() const;
  void set_risk_free_interest_rate(double value);

  private:
  double _internal_risk_free_interest_rate() const;
  void _internal_set_risk_free_interest_rate(double value);

  public:
  // double initial_volatility = 5;
  void clear_initial_volatility() ;
  double initial_volatility() const;
  void set_initial_volatility(double value);

  private:
  double _internal_initial_volatility() const;
  void _internal_set_initial_volatility(double value);

  public:
  // double mean_reversion_rate = 6;
  void clear_mean_reversion_rate() ;
  double mean_reversion_rate() const;
  void set_mean_reversion_rate(double value);

  private:
  double _internal_mean_reversion_rate() const;
  void _internal_set_mean_reversion_rate(double value);

  public:
  // double volatility_of_volatility = 7;
  void clear_volatility_of_volatility() ;
  double volatility_of_volatility() const;
  void set_volatility_of_volatility(double value);

  private:
  double _internal_volatility_of_volatility() const;
  void _internal_set_volatility_of_volatility(double value);

  public:
  // double correlation = 8;
  void clear_correlation() ;
  double correlation() const;
  void set_correlation(double value);

  private:
  double _internal_correlation() const;
  void _internal_set_correlation(double value);

  public:
  // @@protoc_insertion_point(class_scope:options.HestonOptionPricingRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    double underlying_price_;
    double strike_price_;
    double time_to_expiration_;
    double risk_free_interest_rate_;
    double initial_volatility_;
    double mean_reversion_rate_;
    double volatility_of_volatility_;
    double correlation_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_options_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ScholesOptionPricingRequest

// double underlying_price = 1;
inline void ScholesOptionPricingRequest::clear_underlying_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.underlying_price_ = 0;
}
inline double ScholesOptionPricingRequest::underlying_price() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingRequest.underlying_price)
  return _internal_underlying_price();
}
inline void ScholesOptionPricingRequest::set_underlying_price(double value) {
  _internal_set_underlying_price(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingRequest.underlying_price)
}
inline double ScholesOptionPricingRequest::_internal_underlying_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.underlying_price_;
}
inline void ScholesOptionPricingRequest::_internal_set_underlying_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.underlying_price_ = value;
}

// double strike_price = 2;
inline void ScholesOptionPricingRequest::clear_strike_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.strike_price_ = 0;
}
inline double ScholesOptionPricingRequest::strike_price() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingRequest.strike_price)
  return _internal_strike_price();
}
inline void ScholesOptionPricingRequest::set_strike_price(double value) {
  _internal_set_strike_price(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingRequest.strike_price)
}
inline double ScholesOptionPricingRequest::_internal_strike_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.strike_price_;
}
inline void ScholesOptionPricingRequest::_internal_set_strike_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.strike_price_ = value;
}

// double time_to_expiration = 3;
inline void ScholesOptionPricingRequest::clear_time_to_expiration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.time_to_expiration_ = 0;
}
inline double ScholesOptionPricingRequest::time_to_expiration() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingRequest.time_to_expiration)
  return _internal_time_to_expiration();
}
inline void ScholesOptionPricingRequest::set_time_to_expiration(double value) {
  _internal_set_time_to_expiration(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingRequest.time_to_expiration)
}
inline double ScholesOptionPricingRequest::_internal_time_to_expiration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_to_expiration_;
}
inline void ScholesOptionPricingRequest::_internal_set_time_to_expiration(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_to_expiration_ = value;
}

// double risk_free_interest_rate = 4;
inline void ScholesOptionPricingRequest::clear_risk_free_interest_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.risk_free_interest_rate_ = 0;
}
inline double ScholesOptionPricingRequest::risk_free_interest_rate() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingRequest.risk_free_interest_rate)
  return _internal_risk_free_interest_rate();
}
inline void ScholesOptionPricingRequest::set_risk_free_interest_rate(double value) {
  _internal_set_risk_free_interest_rate(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingRequest.risk_free_interest_rate)
}
inline double ScholesOptionPricingRequest::_internal_risk_free_interest_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.risk_free_interest_rate_;
}
inline void ScholesOptionPricingRequest::_internal_set_risk_free_interest_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.risk_free_interest_rate_ = value;
}

// double volatility = 5;
inline void ScholesOptionPricingRequest::clear_volatility() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.volatility_ = 0;
}
inline double ScholesOptionPricingRequest::volatility() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingRequest.volatility)
  return _internal_volatility();
}
inline void ScholesOptionPricingRequest::set_volatility(double value) {
  _internal_set_volatility(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingRequest.volatility)
}
inline double ScholesOptionPricingRequest::_internal_volatility() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.volatility_;
}
inline void ScholesOptionPricingRequest::_internal_set_volatility(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.volatility_ = value;
}

// -------------------------------------------------------------------

// ScholesOptionPricingResponse

// double option_price = 1;
inline void ScholesOptionPricingResponse::clear_option_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.option_price_ = 0;
}
inline double ScholesOptionPricingResponse::option_price() const {
  // @@protoc_insertion_point(field_get:options.ScholesOptionPricingResponse.option_price)
  return _internal_option_price();
}
inline void ScholesOptionPricingResponse::set_option_price(double value) {
  _internal_set_option_price(value);
  // @@protoc_insertion_point(field_set:options.ScholesOptionPricingResponse.option_price)
}
inline double ScholesOptionPricingResponse::_internal_option_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.option_price_;
}
inline void ScholesOptionPricingResponse::_internal_set_option_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.option_price_ = value;
}

// -------------------------------------------------------------------

// HestonOptionPricingRequest

// double underlying_price = 1;
inline void HestonOptionPricingRequest::clear_underlying_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.underlying_price_ = 0;
}
inline double HestonOptionPricingRequest::underlying_price() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.underlying_price)
  return _internal_underlying_price();
}
inline void HestonOptionPricingRequest::set_underlying_price(double value) {
  _internal_set_underlying_price(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.underlying_price)
}
inline double HestonOptionPricingRequest::_internal_underlying_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.underlying_price_;
}
inline void HestonOptionPricingRequest::_internal_set_underlying_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.underlying_price_ = value;
}

// double strike_price = 2;
inline void HestonOptionPricingRequest::clear_strike_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.strike_price_ = 0;
}
inline double HestonOptionPricingRequest::strike_price() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.strike_price)
  return _internal_strike_price();
}
inline void HestonOptionPricingRequest::set_strike_price(double value) {
  _internal_set_strike_price(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.strike_price)
}
inline double HestonOptionPricingRequest::_internal_strike_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.strike_price_;
}
inline void HestonOptionPricingRequest::_internal_set_strike_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.strike_price_ = value;
}

// double time_to_expiration = 3;
inline void HestonOptionPricingRequest::clear_time_to_expiration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.time_to_expiration_ = 0;
}
inline double HestonOptionPricingRequest::time_to_expiration() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.time_to_expiration)
  return _internal_time_to_expiration();
}
inline void HestonOptionPricingRequest::set_time_to_expiration(double value) {
  _internal_set_time_to_expiration(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.time_to_expiration)
}
inline double HestonOptionPricingRequest::_internal_time_to_expiration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_to_expiration_;
}
inline void HestonOptionPricingRequest::_internal_set_time_to_expiration(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_to_expiration_ = value;
}

// double risk_free_interest_rate = 4;
inline void HestonOptionPricingRequest::clear_risk_free_interest_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.risk_free_interest_rate_ = 0;
}
inline double HestonOptionPricingRequest::risk_free_interest_rate() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.risk_free_interest_rate)
  return _internal_risk_free_interest_rate();
}
inline void HestonOptionPricingRequest::set_risk_free_interest_rate(double value) {
  _internal_set_risk_free_interest_rate(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.risk_free_interest_rate)
}
inline double HestonOptionPricingRequest::_internal_risk_free_interest_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.risk_free_interest_rate_;
}
inline void HestonOptionPricingRequest::_internal_set_risk_free_interest_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.risk_free_interest_rate_ = value;
}

// double initial_volatility = 5;
inline void HestonOptionPricingRequest::clear_initial_volatility() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.initial_volatility_ = 0;
}
inline double HestonOptionPricingRequest::initial_volatility() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.initial_volatility)
  return _internal_initial_volatility();
}
inline void HestonOptionPricingRequest::set_initial_volatility(double value) {
  _internal_set_initial_volatility(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.initial_volatility)
}
inline double HestonOptionPricingRequest::_internal_initial_volatility() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.initial_volatility_;
}
inline void HestonOptionPricingRequest::_internal_set_initial_volatility(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.initial_volatility_ = value;
}

// double mean_reversion_rate = 6;
inline void HestonOptionPricingRequest::clear_mean_reversion_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mean_reversion_rate_ = 0;
}
inline double HestonOptionPricingRequest::mean_reversion_rate() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.mean_reversion_rate)
  return _internal_mean_reversion_rate();
}
inline void HestonOptionPricingRequest::set_mean_reversion_rate(double value) {
  _internal_set_mean_reversion_rate(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.mean_reversion_rate)
}
inline double HestonOptionPricingRequest::_internal_mean_reversion_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.mean_reversion_rate_;
}
inline void HestonOptionPricingRequest::_internal_set_mean_reversion_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.mean_reversion_rate_ = value;
}

// double volatility_of_volatility = 7;
inline void HestonOptionPricingRequest::clear_volatility_of_volatility() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.volatility_of_volatility_ = 0;
}
inline double HestonOptionPricingRequest::volatility_of_volatility() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.volatility_of_volatility)
  return _internal_volatility_of_volatility();
}
inline void HestonOptionPricingRequest::set_volatility_of_volatility(double value) {
  _internal_set_volatility_of_volatility(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.volatility_of_volatility)
}
inline double HestonOptionPricingRequest::_internal_volatility_of_volatility() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.volatility_of_volatility_;
}
inline void HestonOptionPricingRequest::_internal_set_volatility_of_volatility(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.volatility_of_volatility_ = value;
}

// double correlation = 8;
inline void HestonOptionPricingRequest::clear_correlation() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.correlation_ = 0;
}
inline double HestonOptionPricingRequest::correlation() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingRequest.correlation)
  return _internal_correlation();
}
inline void HestonOptionPricingRequest::set_correlation(double value) {
  _internal_set_correlation(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingRequest.correlation)
}
inline double HestonOptionPricingRequest::_internal_correlation() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.correlation_;
}
inline void HestonOptionPricingRequest::_internal_set_correlation(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.correlation_ = value;
}

// -------------------------------------------------------------------

// HestonOptionPricingResponse

// double option_price = 1;
inline void HestonOptionPricingResponse::clear_option_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.option_price_ = 0;
}
inline double HestonOptionPricingResponse::option_price() const {
  // @@protoc_insertion_point(field_get:options.HestonOptionPricingResponse.option_price)
  return _internal_option_price();
}
inline void HestonOptionPricingResponse::set_option_price(double value) {
  _internal_set_option_price(value);
  // @@protoc_insertion_point(field_set:options.HestonOptionPricingResponse.option_price)
}
inline double HestonOptionPricingResponse::_internal_option_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.option_price_;
}
inline void HestonOptionPricingResponse::_internal_set_option_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.option_price_ = value;
}

// -------------------------------------------------------------------

// VarianceGammaOptionPricingRequest

// double underlying_price = 1;
inline void VarianceGammaOptionPricingRequest::clear_underlying_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.underlying_price_ = 0;
}
inline double VarianceGammaOptionPricingRequest::underlying_price() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.underlying_price)
  return _internal_underlying_price();
}
inline void VarianceGammaOptionPricingRequest::set_underlying_price(double value) {
  _internal_set_underlying_price(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.underlying_price)
}
inline double VarianceGammaOptionPricingRequest::_internal_underlying_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.underlying_price_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_underlying_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.underlying_price_ = value;
}

// double strike_price = 2;
inline void VarianceGammaOptionPricingRequest::clear_strike_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.strike_price_ = 0;
}
inline double VarianceGammaOptionPricingRequest::strike_price() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.strike_price)
  return _internal_strike_price();
}
inline void VarianceGammaOptionPricingRequest::set_strike_price(double value) {
  _internal_set_strike_price(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.strike_price)
}
inline double VarianceGammaOptionPricingRequest::_internal_strike_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.strike_price_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_strike_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.strike_price_ = value;
}

// double time_to_expiration = 3;
inline void VarianceGammaOptionPricingRequest::clear_time_to_expiration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.time_to_expiration_ = 0;
}
inline double VarianceGammaOptionPricingRequest::time_to_expiration() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.time_to_expiration)
  return _internal_time_to_expiration();
}
inline void VarianceGammaOptionPricingRequest::set_time_to_expiration(double value) {
  _internal_set_time_to_expiration(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.time_to_expiration)
}
inline double VarianceGammaOptionPricingRequest::_internal_time_to_expiration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.time_to_expiration_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_time_to_expiration(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.time_to_expiration_ = value;
}

// double risk_free_interest_rate = 4;
inline void VarianceGammaOptionPricingRequest::clear_risk_free_interest_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.risk_free_interest_rate_ = 0;
}
inline double VarianceGammaOptionPricingRequest::risk_free_interest_rate() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.risk_free_interest_rate)
  return _internal_risk_free_interest_rate();
}
inline void VarianceGammaOptionPricingRequest::set_risk_free_interest_rate(double value) {
  _internal_set_risk_free_interest_rate(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.risk_free_interest_rate)
}
inline double VarianceGammaOptionPricingRequest::_internal_risk_free_interest_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.risk_free_interest_rate_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_risk_free_interest_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.risk_free_interest_rate_ = value;
}

// double drift_rate = 5;
inline void VarianceGammaOptionPricingRequest::clear_drift_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.drift_rate_ = 0;
}
inline double VarianceGammaOptionPricingRequest::drift_rate() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.drift_rate)
  return _internal_drift_rate();
}
inline void VarianceGammaOptionPricingRequest::set_drift_rate(double value) {
  _internal_set_drift_rate(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.drift_rate)
}
inline double VarianceGammaOptionPricingRequest::_internal_drift_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.drift_rate_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_drift_rate(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.drift_rate_ = value;
}

// double volatility = 6;
inline void VarianceGammaOptionPricingRequest::clear_volatility() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.volatility_ = 0;
}
inline double VarianceGammaOptionPricingRequest::volatility() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.volatility)
  return _internal_volatility();
}
inline void VarianceGammaOptionPricingRequest::set_volatility(double value) {
  _internal_set_volatility(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.volatility)
}
inline double VarianceGammaOptionPricingRequest::_internal_volatility() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.volatility_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_volatility(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.volatility_ = value;
}

// double mean_reversion_parameter = 7;
inline void VarianceGammaOptionPricingRequest::clear_mean_reversion_parameter() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mean_reversion_parameter_ = 0;
}
inline double VarianceGammaOptionPricingRequest::mean_reversion_parameter() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.mean_reversion_parameter)
  return _internal_mean_reversion_parameter();
}
inline void VarianceGammaOptionPricingRequest::set_mean_reversion_parameter(double value) {
  _internal_set_mean_reversion_parameter(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.mean_reversion_parameter)
}
inline double VarianceGammaOptionPricingRequest::_internal_mean_reversion_parameter() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.mean_reversion_parameter_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_mean_reversion_parameter(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.mean_reversion_parameter_ = value;
}

// double jump_intensity = 8;
inline void VarianceGammaOptionPricingRequest::clear_jump_intensity() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.jump_intensity_ = 0;
}
inline double VarianceGammaOptionPricingRequest::jump_intensity() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.jump_intensity)
  return _internal_jump_intensity();
}
inline void VarianceGammaOptionPricingRequest::set_jump_intensity(double value) {
  _internal_set_jump_intensity(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.jump_intensity)
}
inline double VarianceGammaOptionPricingRequest::_internal_jump_intensity() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.jump_intensity_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_jump_intensity(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.jump_intensity_ = value;
}

// double jump_size_distribution = 9;
inline void VarianceGammaOptionPricingRequest::clear_jump_size_distribution() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.jump_size_distribution_ = 0;
}
inline double VarianceGammaOptionPricingRequest::jump_size_distribution() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingRequest.jump_size_distribution)
  return _internal_jump_size_distribution();
}
inline void VarianceGammaOptionPricingRequest::set_jump_size_distribution(double value) {
  _internal_set_jump_size_distribution(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingRequest.jump_size_distribution)
}
inline double VarianceGammaOptionPricingRequest::_internal_jump_size_distribution() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.jump_size_distribution_;
}
inline void VarianceGammaOptionPricingRequest::_internal_set_jump_size_distribution(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.jump_size_distribution_ = value;
}

// -------------------------------------------------------------------

// VarianceGammaOptionPricingResponse

// double option_price = 1;
inline void VarianceGammaOptionPricingResponse::clear_option_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.option_price_ = 0;
}
inline double VarianceGammaOptionPricingResponse::option_price() const {
  // @@protoc_insertion_point(field_get:options.VarianceGammaOptionPricingResponse.option_price)
  return _internal_option_price();
}
inline void VarianceGammaOptionPricingResponse::set_option_price(double value) {
  _internal_set_option_price(value);
  // @@protoc_insertion_point(field_set:options.VarianceGammaOptionPricingResponse.option_price)
}
inline double VarianceGammaOptionPricingResponse::_internal_option_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.option_price_;
}
inline void VarianceGammaOptionPricingResponse::_internal_set_option_price(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.option_price_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace options


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_options_2eproto_2epb_2eh
